### ISSUE TITLE
Identification with heteroscedasticity

### ISSUE THREAD

**Issue by AndrewGuiseppe** [bsvars/bsvars#54]
Hello,

To apply the identification approaches introduced in the BSVARS package, should the number of structural parameters be equal to or greater than the number of reduced form parameters? For example, if I have 6 variables,  can I still use these identification approaches to estimate an SVAR model even if the contamprenoues matrix has less than 15 estimated parameters. Would this result in any issues with my identification? 

Thanks a lot

**Comment by donotdespair** [comment]
Hi @AndrewGuiseppe 

Happy to help! Why don't you copy/paste in this thread your setup of the structural matrix and the script for the setup of the model and estimation? It'd be much easier to talk.

Basically, in this package, if only you use a heteroskedastic model, all the `N^2` elements of the $N\times N$ structural matrix `B` can be estimated. I setup, the `B` matrix for such models by `B = matrix(TRUE, N, N)` and provide it as argument `B` to the `specify_*()` functions. The identification via heteroskedasticity should be checked and the package provides some tools for that, and the outcome might need to be standardised (which is on you as no well-established method has been developed in academic literature). When I used the data provided for the package no normalisation was needed though.

Cheers, T

**Comment by AndrewGuiseppe** [comment]
Thank you, @donotdespair, for the detailed answer. I have another question: if we use high-frequency data (i.e., daily or weekly), does this support identification via heteroscedasticity, or is the frequency irrelevant to this identification approach?

Additionally, one of the variables we use exhibits the following pattern:

![data](https://github.com/bsvars/bsvars/assets/152004175/a6d87e39-2560-4e19-ae0b-c47f914d6dab)

Would there be an issue if we included this variable in our SVAR and applied identification via heteroscedasticity?

**Comment by donotdespair** [comment]
Hey @AndrewGuiseppe 

Thanks for the follow up! The id via heteroskedasticity works better the more the variables or shocks are heteroskedastic AND the more the individual paths of structural shocks' conditional variances. I have a paper on this: [Lütkepohl, Woźniak (2020)](https://doi.org/10.1016/j.jedc.2020.103862). So yes, the higher the frequency and the more distinguishing the variables in your SVAR the better! Now, your variable includes a huge drop for COVID. If other variables have this pattern as well, then it is likely that other variables will have a higher heteroskedasticity for this period as well. Therefore, other periods would need to provide distinguishing volatility patterns.

Otherwise, your variable is likely to be unit-root non-stationary. Test that using, e.g., a Dickey-Fuller test. Include the findings by setting up the argument `stationary` of the `specify_bsvar*()` function accordingly.

To investigate identification via heteroskedasticity:
1. Read my paper and the related literature.
2. Estimate your model as you wish.
3. Use function `compute_conditional_sd()` to compute and then write your own code to plot shocks' volatilities. Analyse visually if the heteroskedastic patterns are different.
4. Use function `verify_volatility()` to test if the structural shocks are heteroskedastic. 

And then decide if your model is identified via heteroskedasticity, and act accordingly.

:)

Does this help?

Cheers, T
