### ISSUE TITLE
Monthly data?

### ISSUE THREAD

**Issue by RightHandOfDoom** [bsvars/bsvars#83]
Hello! First: thanks for the 3.0.0 release. The changes are great and I am looking already forward to what comes next.

One question: the examples use mostly quarterly data. However, for an upcoming project, I will have to use use monthly data. My question is if you recommend making adjustments to the hyperparameters or in the prior specification.

[the data I'll be using will be quite volatile, using the TED-Spread & VIX-Index, maybe it makes sense to increase the posterior's sensitivity to the data?]. Any hints are welcome and thank you very much !!

**Comment by donotdespair** [comment]
Hey @RightHandOfDoom 

Thanks so much for your ongoing interest and support! I really really appreciate it! Thank you!

In general, the coded models fancy a v flexible three-level prior structures for autoregressive parameters $\mathbf{A}$ and the structural matrix $\mathbf{B}_0$. They should handle monthly data easily. We have checked that extensively working on another project https://arxiv.org/abs/2311.05883 where we had a 6-variable monthly macro system for US. The setup was working really well without adjustments. We don't report any such results in the paper though as the focus is on TVI that is not covered in the **bsvars** package.

You can find more info about the hierarchical prior in our work https://arxiv.org/abs/2404.11057 as the package implements exactly this paper (and other heteroskedastic specifications). Then, specify your model running, say,
```
data(us_fiscal_lsuw)
specification  = specify_bsvar_sv$new(us_fiscal_lsuw)
```
and looking into the content of `specification$prior`. For instance, `specification$prior$A` contains the mean of the normal prior for the autoregressive matrix $\mathbf{A}$. Then, elements `specification$prior$hyper_*` contain the setup of the hierarchical specification. One could modify them and see how this affects the results in the prior robustness checks. The only thing is that if one wants to verify heteroskedasticity using `verify_volatility()`, then `specification$prior$sv_a_` must be greater than 0.5. Otherwise the procedure is not valid. 

But as I am saying, the prior structure is v flexible and many layers of shrinkage are estimated. I would be surprised if the results were sensitive to the prior hyper-parameters from `specification$prior` that must to be fixed. 

Good luck with your project! Feel free to reach out if you had more questions.

Greetings, Tomasz

**Comment by RightHandOfDoom** [comment]
Hello Tomasz,
thank you for the helpful response, very much appreciated!
